language: c
compiler:
 - gcc

before_install: 
 - sudo apt-get install -y build-essential p7zip-full
 - wget http://downloadmirror.intel.com/23197/eng/Board_Support_Package_Sources_for_Intel_Quark_v1.0.0.7z
 - 7z x Board_Support_Package_Sources_for_Intel_Quark_v1.0.0.7z
 - ls
 - tar xvf meta-clanton_v1.0.0.tar.gz
 - cd meta-clanton_v1.0.0
 - ./setup.sh
install: true
script: true

