language: c
compiler:
 - gcc

env: 
  global: 
  - secure: "YgCtaC0QQb+Zzsg48hpd9PyFSqSpXjg1AEEvNvDIqO4Ao+raPmaCGsMii8WJIoXEiYDFSe0RMliyvIhzmutjJ/0M4SETpW/o+Eq6ydNrdmZB6LpK1DGZq/mFkrheCD3ggMPBK4aBERaR1pHe5Pb1S9HAaIoBcpXn6u0SXx8o2V0="

before_install: 
 - sudo apt-get install -y build-essential p7zip-full diffstat texinfo chrpath
 - sudo apt-get remove -y git
 - wget https://github.com/alan-donnelly/galileo-git/archive/1.8.1.2.tar.gz -O galileo-git-1.8.1.2.tar.gz
 - tar -xf galileo-git-1.8.1.2.tar.gz
 - cd galileo-git-1.8.1.2
 - "sed -i -e \"s/install: all/install:/\" Makefile"
 - sudo make install 
 - cd ..
 - rm -rf galileo-git-1.8.1.2
 - sudo ln -s /usr/local/bin/git /usr/bin/git
 - git --version

install: 
 - mkdir /tmp/bsp
 - sudo mount --bind /home/travis/build/CoderDojo/galileo-system-image /tmp/bsp
 - cd /tmp/bsp 
 - wget http://downloadmirror.intel.com/23197/eng/Board_Support_Package_Sources_for_Intel_Quark_v1.0.0.7z
 - 7z x Board_Support_Package_Sources_for_Intel_Quark_v1.0.0.7z
 - sha1sum -c sha1sum.txt
 - tar xkvf meta-clanton_v1.0.0.tar.gz
 - cd meta-clanton_v1.0.0
 - ./setup.sh
 - . poky/oe-init-build-env yocto_build

script: ( (sleep 2400; killall -s SIGINT python; sleep 60; killall -s SIGINT python) & (bitbake image-full-galileo ) )

after_script:
 - git remote set-url --push origin https://$GH_APP_TOKEN@github.com/CoderDojo/galileo-system-image.git
 - git config user.name alan-donnelly
 - git config user.email ci@travis-ci.org
 - cd /home/travis/build/CoderDojo/galileo-system-image
 - git add -f meta-clanton_v1.0.0/yocto_build/sstate-cache/*
 - git commit -a -m 'Updating shared build state. $CI_SKIP'
 - git push 


after_success:
 - export CI_SKIP="[ci skip]"
