language: c
compiler:
 - gcc

env: 
  global: 
  - secure: CQK9KGcInMoZBRXtVkvYrdqZvXY8kdJ+fTE9Rv/iXzopfMkW3eNDS1QlavZZmZjUvPQy9nRdTicQJzVr9rmpMHNb35Cy35HBdJ4KhJoiKkaTlt/H64b0UOZAZhoie7R3fYd89VW3WXzHCsdW945jvXZjxzm+HXnLdHPSEMjOgz0=

before_install: 
 - sudo apt-get install -y build-essential p7zip-full diffstat texinfo chrpath
 - sudo apt-get remove -y git
 - wget https://github.com/alan-donnelly/galileo-git/archive/1.8.1.2.tar.gz -O galileo-git-1.8.1.2.tar.gz
 - tar -xf galileo-git-1.8.1.2.tar.gz
 - cd galileo-git-1.8.1.2
 - "sed -i -e \"s/install: all/install:/\" Makefile"
 - sudo make install 
 - cd ..
 - rm -rf galileo-git-1.8.1.2
 - sudo ln -s /usr/local/bin/git /usr/bin/git
 - which git
 - git --version
 - cd /home/travis/build/CoderDojo/galileo-system-image
 - mkdir -p meta-clanton_v1.0.0/sstate-cache
 - echo "CoderDojo meta-clanton_v1.0.0" > meta-clanton_v1.0.0/VERSION
 - git remote set-url --push origin https://$GH_APP_TOKEN@github.com/CoderDojo/galileo-system-image.git
 - git config user.name alan-donnelly
 - git config user.email alan.donnelly@gmail.com
 - git checkout -b 'v1.0.0'
 - git add -f meta-clanton_v1.0.0/sstate-cache
 - git commit -a -m "Updating shared build state. [ci skip]"
 - git push

install: 
 - mkdir /tmp/bsp
 - mount --bind /home/travis/build/CoderDojo/galileo-system-image /tmp/bsp
 - cd /tmp/bsp 
 - wget http://downloadmirror.intel.com/23197/eng/Board_Support_Package_Sources_for_Intel_Quark_v1.0.0.7z
 - 7z x Board_Support_Package_Sources_for_Intel_Quark_v1.0.0.7z
 - sha1sum -c sha1sum.txt
 - tar xvf meta-clanton_v1.0.0.tar.gz
 - ./setup.sh
 - . poky/oe-init-build-env yocto_build

script: ( cmdpid=$BASHPID; (sleep 2700; kill $cmdpid) & exec bitbake image-full-galileo )

after_script:
 - cd /home/travis/build/CoderDojo/galileo-system-image
 - git checkout -b 'v1.0.0'
 - git add -f meta-clanton_v1.0.0/sstate-cache
 - git commit -a -m 'Updating shared build state. [ci skip]'
 - git push